app: kegeye
frameworkVersion: '3'

service: kegeye
org: hbjydev

provider:
  name: aws
  runtime: go1.x

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  hello:
    handler: bin/sls
    environment:
      KE_GITHUB_TOKEN: "${param:githubToken}"
    events:
      - httpApi:
          path: /
          method: any
      - httpApi:
          path: /{proxy+} 
          method: any
